# Generated by Django 3.2.1 on 2021-05-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskitapp', '0002_auto_20210507_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_table',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
