# Generated by Django 3.2.1 on 2021-05-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskitapp', '0003_company_table_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_table',
            old_name='pictur_id',
            new_name='picture_id',
        ),
    ]
