# Generated by Django 3.2.1 on 2021-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskitapp', '0004_rename_pictur_id_picture_table_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/maskitapp/images'),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/maskitapp/images'),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/maskitapp/images'),
        ),
        migrations.DeleteModel(
            name='picture_table',
        ),
    ]
