# Generated by Django 3.2.1 on 2021-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskitapp', '0006_alter_history_table_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/media/maskitapp/images'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/media/maskitapp/images'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/media/maskitapp/images'),
        ),
    ]
