# Generated by Django 3.2.1 on 2021-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskitapp', '0007_auto_20210509_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='image1',
            field=models.ImageField(null=True, upload_to='maskitapp/images'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='image2',
            field=models.ImageField(null=True, upload_to='maskitapp/images'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='image3',
            field=models.ImageField(null=True, upload_to='maskitapp/images'),
        ),
    ]
